### ISSUE TITLE
xscreenruler exits without an error if the X display cannot be opened.

### ISSUE THREAD

**Issue by vext01** [6d7367/xscreenruler#2]
```
$ unset DISPLAY
$ xscreenruler 
$ 
```

**Comment by omar-polo** [comment]
Technically, it exits with an error

    $ unset DISPLAY
    $ ./xscreenruler
    $ echo $?
    255

main.c:85

    display = XOpenDisplay(NULL);
    if (display == NULL) { exit(-1); }

although an `errx(1, "can't open display");`  may be better.

p.s. I found this thanks to your port submission :)

**Comment by vext01** [comment]
@omar-polo see that PR ^

**Comment by 6d7367** [comment]
Thanks!
